export class AirSupportSystem {
  constructor({world,getUnits,cards,decks,aircraft,airDefense,fortificationDamage,airSuperiority,fogOfWar}){Object.assign(this,{world,getUnits,cards,decks,aircraft,airDefense,fortificationDamage,airSuperiority,fogOfWar});this.state={};this.cap={};}
  configure(scenario){this.state={};const cfg=scenario?.airSupport??scenario?.map?.airSupport??{};for(const side of ['chinese','japanese','german','soviet','american','un']){const s=cfg[side];if(!s?.enabled)continue;const deck=this.decks[s.deckId];if(!deck)continue;this.state[side]={deckId:s.deckId,points:s.points??99,cards:Object.fromEntries(deck.cards.map(id=>[id,Number(s.uses?.[id]??this.cards[id]?.uses??1)]))};}}
  available(side){const s=this.state[side];if(!s)return[];return Object.entries(s.cards).filter(([,n])=>n>0).map(([id,n])=>({...this.cards[id],remaining:n}));}
  dist(a,b){const aq=+a.q,ar=+a.r,bq=+b.q,br=+b.r;return (Math.abs(aq-bq)+Math.abs(aq+ar-bq-br)+Math.abs(ar-br))/2;}
  enemySide(side,enemies){return enemies[0]?String(enemies[0].faction??enemies[0].side):'';}
  falloff(card,d){if(!card.radius)return 1;return d===0?1:Math.max(.35,1-d/(Number(card.radius)+1)*.6);}
  execute(side,cardId,target){
    const st=this.state[side],card=this.cards[cardId];if(!st||!card||!(st.cards[cardId]>0))return {ok:false,message:'航空卡不可用'};
    const plane=this.aircraft[card.aircraft]??{},all=this.getUnits?.()??[],enemies=all.filter(u=>u.offMap!==true&&String(u.faction??u.side)!==String(side));
    const defender=this.enemySide(side,enemies),aa=this.airDefense?.threat(target,defender,plane.altitude??'low')??{score:0,sources:[],disruption:0};
    const air=this.airSuperiority?.enemyPressure(side,target)??{score:0,attackPenalty:0,accuracyPenalty:0,rangePenalty:0,sources:[]};
    const aaPenalty=Math.min(.70,Number(aa.disruption??aa.score/500));const attackFactor=Math.max(.18,(1-aaPenalty)*(1-air.attackPenalty));const accuracyFactor=Math.max(.25,1-air.accuracyPenalty);st.cards[cardId]--;
    if(card.missionType==='cap'){this.airSuperiority?.addCAP(side,target,card,plane);this.cap[side]=Number(card.duration??2);return {ok:true,message:`${card.name}已在 (${target.q},${target.r}) 建立制空区，半径${card.controlRadius??plane.controlRadius??8}格，持续${card.duration??2}回合`};}
    if(card.missionType==='recon'){const radius=Math.max(2,Number(card.radius??8)-air.rangePenalty);this.fogOfWar?.reveal(target.q,target.r,radius,2);return {ok:true,message:`${card.name}完成：揭示目标周边${radius}格；敌制空压力${Math.round(air.score)}，防空威胁${Math.round(aa.score)}`};}
    if(card.missionType==='supply'){const u=all.find(x=>String(x.faction??x.side)===String(side)&&this.dist(x,target)<=0);if(u){u.ammo=100;u.morale=Math.min(100,Number(u.morale??70)+15);return {ok:true,message:`${card.name}完成：${u.name} 弹药补满，士气恢复`};}return {ok:true,message:`${card.name}抵达目标区，但该格没有己方单位`};}
    if(card.missionType==='paradrop'){const occupied=all.some(x=>x.offMap!==true&&+x.q===+target.q&&+x.r===+target.r),terrain=String(this.world?.terrainAt?.(+target.q,+target.r)??'plain');if(occupied||['water','mountain','swamp'].includes(terrain))return {ok:false,message:'该地形/地块不适合空降（卡牌未消耗）',refund:true};const effective=Math.max(.15,attackFactor*accuracyFactor);all.push({id:`AIRBORNE_${Date.now()}`,name:card.aircraft==='LI2'?'苏军空降兵测试营':'空降兵测试营',faction:side,type:'infantry',echelon:'battalion',q:+target.q,r:+target.r,strength:Math.round(360*effective),maxStrength:400,attack:8,defense:6,movement:4,range:1,morale:60,ammo:70,airborneDisorganized:2,actionPoints:0,hasActed:true});return {ok:true,message:`${plane.name??card.name}空降完成；防空/制空干扰${Math.round((1-effective)*100)}%，部队处于集结状态`};}
    const radius=Number(card.radius??0);let hits=0,total=0,fortDamage=0,fortDestroyed=0,bridgeDamage=0,bridgeDestroyed=0,wallDamage=0;
    for(const u of enemies){const d=this.dist(u,target);if(d>radius)continue;const mult=this.falloff(card,d);let base=Number(plane.groundAttack??50);if(card.missionType==='anti_armor'&&/tank|armor|装甲|坦克/i.test(String(u.type)+' '+String(u.name)))base=Number(plane.armorAttack??base);const dmg=Math.max(1,Math.round(base*attackFactor*mult*.8));const before=Number(u.strength??100);u.strength=Math.max(0,before-dmg);u.morale=Math.max(0,Number(u.morale??70)-Math.round(Number(plane.suppression??40)/5*mult));hits++;total+=before-u.strength;}
    const precision=Number(plane.accuracy??70)/70*accuracyFactor;
    for(const f of (this.world?.fortifications??[])){const d=this.dist(f,target);if(d>radius||String(f.status)==='destroyed')continue;const res=this.fortificationDamage?.damageFort(f,Number(plane.fortificationAttack??0)*attackFactor,this.falloff(card,d)*precision);if(res){fortDamage+=res.damage;if(res.destroyed)fortDestroyed++;}}
    for(const b of (this.world?.bridges??[])){const d=this.dist(b,target);if(d>radius||String(b.status)==='destroyed')continue;const res=this.fortificationDamage?.damageBridge(b,Number(plane.bridgeAttack??plane.fortificationAttack??0)*attackFactor,this.falloff(card,d)*precision);if(res){bridgeDamage+=res.damage;if(res.destroyed)bridgeDestroyed++;}}
    const wr=this.fortificationDamage?.damageWallsAt(+target.q,+target.r,Number(plane.wallAttack??plane.fortificationAttack??0)*attackFactor,precision);if(wr)wallDamage+=wr.damage;
    return {ok:true,message:`${card.name}完成：单位命中${hits}个/损失${total}；工事损伤${fortDamage}${fortDestroyed?`（摧毁${fortDestroyed}）`:''}；桥梁损伤${bridgeDamage}${bridgeDestroyed?`（摧毁${bridgeDestroyed}）`:''}${wallDamage?`；城墙损伤${wallDamage}`:''}；防空威胁${Math.round(aa.score)}；敌制空压力${Math.round(air.score)}${air.sources.length?'（'+air.sources.join('、')+'）':''}`};
  }
}
